mail:
  image: node:latest
  command: "npm run mail-server"
  working_dir: /app
  links:
   - db
  environment:
   - NODE_ENV=docker
  volumes:
   - .:/app
  ports:
   - "2525:2525"

db:
  image: rethinkdb:latest
  expose:
   - 28015
  ports:
   - "8081:8080"
   - "28015:28015"
   - "28016:28016"
